# Site settings
title: Aaron Lahey
email: aaron.lahey@gmail.com
description: Development Blog
url: "http://www.aaronlahey.com"
twitter_username: aaronlahey
github_username:  aaronlahey

# Build settings
markdown: kramdown
